app:
  product: "auttar-portal-cliente"
  name: "customer-portal-test-e2e"
  baseVersion: "0.0"
  tecnology: "cypress"
  repositoryType: "app"
  functionalTestingTool: "cypress"
  skip_versioning: "false"
  notificationType: "mail"
  mailTo: ""
